### ISSUE TITLE
Where is the implementation of domain balance loss?

### ISSUE THREAD

**Issue by BJTUJia** [WangWenhao0716/DomainMix#3]
dear author, thanks for this nice repo. However, I am unable to locate the "domain balance loss" anywhere in the codebase. Can you give me a guide on this? Thanks!

**Comment by WangWenhao0716** [comment]
https://github.com/WangWenhao0716/DomainMix/blob/main/dg/trainers.py
Line 121 - Line 122

**Comment by BJTUJia** [comment]
Thanks, I see.
